[project]
name = "data-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faker>=37.8.0",
    "pandas>=2.3.2",
    "polars>=1.33.1",
    "pydantic>=2.11.9",
    "pydantic-settings>=2.10.1",
]
