"""This is a module for describing possible positions in each department."""


DEPARTMENT_POSITION_MAPPING = {
    "IT": [
        "Software Engineer",
        "System Administrator",
        "DevOps Engineer",
        "Data Scientist",
        "Network Engineer",
        "IT Support Specialist",
        "Cybersecurity Analyst",
        "Database Administrator",
        "Cloud Solutions Architect",
        "Web Developer",
    ],
    "HR": [
        "HR Manager",
        "Recruiter",
        "Training Coordinator",
        "Compensation and Benefits Specialist",
        "Employee Relations Specialist",
        "HR Generalist",
        "Talent Acquisition Specialist",
        "Payroll Specialist",
        "HR Analyst",
        "Diversity and Inclusion Officer",
    ],
    "Finance": [
        "Financial Analyst",
        "Accountant",
        "Auditor",
        "Controller",
        "Treasurer",
        "Budget Analyst",
        "Tax Specialist",
        "Investment Analyst",
        "Credit Analyst",
        "Payroll Manager",
    ],
    "Marketing": [
        "Marketing Manager",
        "Content Strategist",
        "SEO Specialist",
        "Social Media Manager",
        "Brand Manager",
        "Market Research Analyst",
        "Digital Marketing Specialist",
        "Product Marketing Manager",
        "Email Marketing Specialist",
        "Public Relations Specialist",
    ],
    "Sales": [
        "Sales Manager",
        "Account Executive",
        "Sales Representative",
        "Business Development Manager",
        "Sales Analyst",
        "Customer Success Manager",
        "Inside Sales Representative",
        "Field Sales Representative",
        "Sales Operations Coordinator",
        "Territory Sales Manager",
    ],
    "Operations": [
        "Operations Manager",
        "Logistics Coordinator",
        "Supply Chain Analyst",
        "Production Supervisor",
        "Quality Control Specialist",
        "Inventory Manager",
        "Facilities Manager",
        "Project Manager",
        "Process Improvement Specialist",
        "Operations Analyst",
    ],
    "Customer Service": [
        "Customer Service Representative",
        "Customer Support Specialist",
        "Call Center Manager",
        "Technical Support Specialist",
        "Client Relations Manager",
        "Help Desk Technician",
        "Customer Success Specialist",
        "Service Delivery Manager",
        "Customer Experience Analyst",
        "Support Team Lead",
    ],
    "Legal": [
        "Corporate Lawyer",
        "Paralegal",
        "Compliance Officer",
        "Legal Assistant",
        "Contract Manager",
        "Intellectual Property Lawyer",
        "Litigation Specialist",
        "Regulatory Affairs Specialist",
        "Legal Analyst",
        "Risk Management Specialist",
    ],
    "Research & Development": [
        "R&D Manager",
        "Research Scientist",
        "Product Development Engineer",
        "Innovation Specialist",
        "Lab Technician",
        "Clinical Research Coordinator",
        "R&D Analyst",
        "Materials Scientist",
        "Biotechnologist",
        "Chemical Engineer",
    ],
}